apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: edmcs8hi5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/edmcs8hi5-java-springboot-gitops